config/routes.rb
Rails.application.routes.draw do
  
  scope 'mercadocampesino' do
    devise_scope :usuario do
      get 'sign_out' => 'devise/sessions#destroy', as: 'sign_out'

      # El siguiente para superar mala generación del action en el formulario
      # cuando se autentica mal (genera 
      # /puntomontaje/puntomontaje/usuarios/sign_in )
      if (Rails.configuration.relative_url_root != '/') 
        ruta = File.join(Rails.configuration.relative_url_root, 
                         'usuarios/sign_in')
        post ruta, to: 'devise/sessions#create'
        get  ruta, to: 'devise/sessions#new'
      end
      get 'sign_up' => 'registrations#new', as: :sign_up
    end

    devise_for :usuarios, module: :devise, 
      controllers: { registrations: "registrations" }
    #devise_for :usuarios, :skip => [:registrations], module: :devise
    as :usuario do
      get 'usuarios/edit' => 'devise/registrations#edit', 
        :as => 'editar_registro_usuario'    
      put 'usuarios/:id' => 'devise/registrations#update', 
        :as => 'registro_usuario'            
    end
    resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' } 
        
    post 'usuarios/crea' => 'usuarios#create', :as => 'crea_usuario'           
    patch 'usuarios/:id/actualiza' => 'usuarios#update', 
      :as => 'actualiza_usuario'           
    get 'usuarios/reconfirma' => 'usuarios#reconfirma'

    root 'sip/hogar#index'
  end

  mount Sip::Engine, at: "/mercadocampesino"
end

app/views/layouts/application.html.erb
<% content_for :titulo do %>
    <%= Sip.titulo %>
<% end %>

<% content_for :menu do %>
  <%= grupo_menus do %>
    <% if !current_usuario.nil? %>
      <%= opcion_menu "Productos", "#" %>
      <%= opcion_menu "Transporte", "#" %>
      <%= opcion_menu "Compran", "#" %>
    <% end %>
  <% end %>
  <%= grupo_menus empuja: :derecha do %>
    <% if current_usuario %>
      <%= despliega_abajo "Administrar" do %>  
        <%= opcion_menu "Perfil", main_app.editar_registro_usuario_path,
          desplegable: true %>
        <% if can? :manage, ::Usuario %>
          <%= opcion_menu "Usuarios", main_app.usuarios_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, :tablasbasicas %>
          <%= opcion_menu "Tablas Básicas", 
            sip.tablasbasicas_path, desplegable: true %>
        <% end %>
        <% if can? :manage, Sip::Respaldo7z %>
          <%= opcion_menu "Respaldo cifrado", sip.respaldo7z_path,
            desplegable: true %>
        <% end %>
        <%= opcion_menu "Ayuda CA", sip.ayuda_controldeacceso_path,
          desplegable: true %>
        <%= opcion_menu "Salir #{current_usuario.nusuario}", 
          main_app.sign_out_path, desplegable: true %>
      <% end %>
    <% else %>
      <%= opcion_menu "Acerca de", sip.acercade_path %>
      <%= opcion_menu "Iniciar Sesión", main_app.new_usuario_session_path %> 
      <%= opcion_menu "Inscribirse", main_app.sign_up_path %> 
    <% end %>
  <% end %>
<% end %>

<% content_for :piedepagina do %>
  <p><span class='derechos'>Aplicación web de 
<a href='https://github.com/pasosdeJesus/jn635_pdJ'>código abierto</a> desarrollada por Pasos de Jesús. 2020</p>
  </span></p>
<% end %>

<%= render template: "layouts/sip/application" %>